### ISSUE TITLE
Broken link on readme

### ISSUE THREAD

**Issue by lbellomo** [michalmuskala/antidote#193]
In [Benchmarks](https://github.com/michalmuskala/jason/blob/bba1c30e0d610b258a22a69913282e0d10f07b9b/README.md#benchmarks) the links to HTML reports for the benchmark are broken:
- http://michal.muskala.eu/jason/decode.html
- http://michal.muskala.eu/jason/encode.html

I could not find a copy in Internet Archive to replace them.

**Comment by michalmuskala** [comment]
This happens to be a duplicate of #106. I'm going to close this one and continue discussion there
